### PR TITLE
add change language

### PR DESCRIPTION
**Pull request by jferdi24**

### CODE REVIEW

**Comment by JerrySievert** [comment]
this would be a fantastic addition - my only concern is that your editor altered the spacing on almost every line, can you fix that, then i'd be happy to merge!

**Comment by jferdi24** [comment]
hello, what happens is to fix the declaration of arrays used for formatting dates, and added a function that does is replace the arrays, so the lines are relocated

**Comment by JerrySievert** [comment]
i understand that, but if you look at the split view (https://github.com/JerrySievert/date-utils/pull/51/files) -> click on split view, you will see that your editor appears to have affected much more than that.

**Comment by jferdi24** [comment]
if you look closely, has not changed greatest thing is that my editor added some spaces, but the code remains the same

**Comment by JerrySievert** [comment]
i realize that the code remains the same, but it alters history.

**Comment by jferdi24** [comment]
I understand, please check the last change, pull request

**Pull request closed without merging**
