### PR TITLE
add language

### PR DESCRIPTION
**Pull request by jferdi24**

### CODE REVIEW

**Comment by JerrySievert** [comment]
much much better, thank you!

one final request, can you please add tests just to make sure that the languages work in the tests?

thanks much.

**Comment by JerrySievert** [comment]
also, your changes have caused 76 of the tests to fail - can you please correct that?

**Comment by JerrySievert** [comment]
ok, it's evening where i am at, so i will check out your branch tomorrow and see if i can get something started to help you along your way.

we'll get this working.

**Comment by jferdi24** [comment]
ok

**Comment by JerrySievert** [comment]
@jferdi24 here is a skeleton of testing languages for date-utils:

https://gist.github.com/JerrySievert/fb5ca4a73e71b3364da7

you will want to copy that pattern for all of the tests.

in addition, you will want to change line 42 of package.json to the following:

```
    "test": "vows -i --spec"
```

this will isolate the tests, and allow for everything else to pass.

**Comment by jferdi24** [comment]
I done test correctly

**Comment by jferdi24** [comment]
what happened?

**Comment by JerrySievert** [comment]
i am trying to find time to accept the pull request and get a release together.

**Pull request merged**
