### PR TITLE
Fix class documentation closes #62

### LINKED ISSUE #62: Method getMonthAbbrNameFromNumber doesn't exists
The method getMonthAbbrNameFromNumber refered in [documentation](https://jerrysievert.github.io/date-utils/Date.html) does not exists in class.

### PR DESCRIPTION
**Pull request by Godoy**

### CODE REVIEW

**Comment by Godoy** [comment]
I fixed #57 in this same pull request because both fixes are just changes names.

With issue: https://jsfiddle.net/adrianogodoy/33oz5kwg/

With fix, I changed:
juin (june) - keep "jui"
juillet (july) - "jul"
https://jsfiddle.net/adrianogodoy/8vdgzqv9/

**Comment by JerrySievert** [comment]
awesome! i'll get this and the other pull request merged shortly, and a release pushed out.

**Comment by JerrySievert** [comment]
looks like merging your other pull request added conflicts.

any chance you can fix that, then i'll merge?

thanks!

**Comment by Godoy** [comment]
Done! :smile:

**Pull request merged**
